### ISSUE TITLE
getDeviceProperties(gpuid).freeGlobalMem doesn't take the GPU id into account

### ISSUE THREAD

**Issue by fmassa** [torch/cutorch#130]
The field freeGlobalMem in function getDeviceProperties calls cudaMemGetInfo, which outputs the available memory in the current device. Thus, the gpuid is not taken into account in this field, unless one manually calls cutorch.setDevice(gpuid) before (or putting it inside getDeviceProperties and then restoring to the previous gpu after this call). Is there a better way to solve this problem, without needing to set the device in each call to getDeviceProperties ?

**Comment by soumith** [comment]
there is cutorch.getMemoryUsage() but that also assumes the current device.
https://github.com/torch/cutorch/blob/master/init.c#L515

I'll patch that to take a device argument

**Comment by soumith** [comment]
fixed.

cutorch.getMemoryUsage() -- current device
cutorch.getMemoryUsage(2) -- mem usage of device 2

**Comment by fmassa** [comment]
Thanks! But the problem persists inside getDeviceProperties. Should this field be removed from there, as since https://github.com/torch/cutorch/commit/41006b8b96c7b91ac7175b60322b2c61b3e2af9d  there is this getMemoryUsage function ?

**Comment by soumith** [comment]
i could do the same  for getDeviceProperties if you'd like.

**Comment by fmassa** [comment]
It's not really a big deal, I didn't even knew about getDeviceProperties before today and I think almost nobody uses it to get the memory usage (especially now with this getMemoryUsage function). But I think that if getDeviceProperties has a field for the available memory, then it should output the correct information regarding the GPU id, especially as the fix is going to be a simply copy-paste from https://github.com/torch/cutorch/pull/132 . What do you think ?
