### ISSUE TITLE
THCTensorIndex.cu: cannot overload functions distinguished from return type alone

### ISSUE THREAD

**Issue by cpdurham** [torch/cutorch#508]
Commented on the commit, but thought this might be better, installed from scratch (while https://github.com/torch/cutorch/commit/a0608f6331fc82cacd6ee3285f338c62406529a1 was last commit)

ubuntu 16.04, cuda 8 (with patch) compiling for titan x

```
Installing https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 195, done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 195 (delta 59), reused 97 (delta 45), pack-reused 0
Receiving objects: 100% (195/195), 184.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (59/59), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/cdurham/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/cdurham/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/cdurham/torch/install
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "6.5") 
-- MAGMA not found. Compiling without MAGMA support
-- Autodetected CUDA architecture(s): 5.2
-- got cuda version 8.0
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS: -gencode;arch=compute_52,code=sm_52;-DCUDA_HAS_FP16=1
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cutorch-scm-1-204/cutorch/build
[  1%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[  2%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
[  3%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[  4%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
[  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
[  8%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathPairwise.cu.o
[ 10%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
[ 10%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathBlas.cu.o
[ 11%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath2.cu.o
[ 12%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[ 14%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathMagma.cu.o
[ 15%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathPointwise.cu.o
[ 16%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathReduce.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathScan.cu.o
[ 18%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorIndex.cu.o
[ 20%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorConv.cu.o
[ 21%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorRandom.cu.o
/tmp/luarocks_cutorch-scm-1-204/cutorch/lib/THC/THCTensorIndex.cu(207): error: cannot overload functions distinguished by return type alone

1 error detected in the compilation of "/tmp/tmpxft_000020ce_00000000-5_THCTensorIndex.cpp4.ii".
CMake Error at THC_generated_THCTensorIndex.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_cutorch-scm-1-204/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorIndex.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:161: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorIndex.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorIndex.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:172: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
```

**Comment by soumith** [comment]
fixed via https://github.com/torch/cutorch/commit/3624cb9a5be6646d172fa686ce423ff2c9c3b3e6

**Comment by cpdurham** [comment]
Wow, thanks for the quick fix!

**Comment by positlabs** [comment]
I'm still getting this error when installing via https://github.com/torch/distro.git

Should I pull from that commit hash instead?
