### ISSUE TITLE
'luarocks install cutorch' error on Ubuntu 14.04

### ISSUE THREAD

**Issue by satwikkottur** [torch/cutorch#541]
Gets stuck at 39% with several such messages:

[ 39%] /tmp/luarocks_cutorch-scm-1-9484/cutorch/lib/THC/THCTensorRandom.cu(250): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

**Comment by soumith** [comment]
what CUDA version are you on?

**Comment by satwikkottur** [comment]
CUDA v7.0

**Comment by soumith** [comment]
i'm checking it now

**Comment by soumith** [comment]
fixed now

**Comment by BTNC** [comment]
I'm very sorry for the compilation error, it is an error introduced by my ptrdiff_t change. I will fix it.

**Comment by ambarpal** [comment]
@BTNC @soumith 
I think the issue is not fixed completely. I'm still getting the error on Ubuntu 15.04, CUDA v7.0
I installed torch from scratch, following instructions on the getting started page

> /home/ambar/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(250): error: more than one instance of overloaded function "min" matches the argument list:
>             function "min(int, int)"
>             function "min(unsigned int, unsigned int)"
>             function "min(int, unsigned int)"
>             function "min(unsigned int, int)"
>             function "min(long long, long long)"
>             function "min(unsigned long long, unsigned long long)"
>             function "min(long long, unsigned long long)"
>             function "min(unsigned long long, long long)"
>             function "min(float, float)"
>             function "min(double, double)"
>             function "min(float, double)"
>             function "min(double, float)"
>             argument types are: (ptrdiff_t, ptrdiff_t)
> .....
> /home/ambar/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(323): error: more than one instance of overloaded function "min" matches the argument list:
>             function "min(int, int)"
>             function "min(unsigned int, unsigned int)"
>             function "min(int, unsigned int)"
>             function "min(unsigned int, int)"
>             function "min(long long, long long)"
>             function "min(unsigned long long, unsigned long long)"
>             function "min(long long, unsigned long long)"
>             function "min(unsigned long long, long long)"
>             function "min(float, float)"
>             function "min(double, double)"
>             function "min(float, double)"
>             function "min(double, float)"
>             argument types are: (ptrdiff_t, ptrdiff_t)
> /home/ambar/torch/extra/cutorch/lib/THC/THCTensorRandom.cu(338): error: more than one instance of overloaded function "min" matches the argument list:
>             function "min(int, int)"
>             function "min(unsigned int, unsigned int)"
>             function "min(int, unsigned int)"
>             function "min(unsigned int, int)"
>             function "min(long long, long long)"
>             function "min(unsigned long long, unsigned long long)"
>             function "min(long long, unsigned long long)"
>             function "min(unsigned long long, long long)"
>             function "min(float, float)"
>             function "min(double, double)"
>             function "min(float, double)"
>             function "min(double, float)"
>             argument types are: (ptrdiff_t, ptrdiff_t)
> 7 errors detected in the compilation of "/tmp/tmpxft_000073a4_00000000-7_THCTensorRandom.cpp1.ii".

**Comment by hworang77** [comment]
I am also having the same error.

/tmp/luarocks_cutorch-scm-1-4622/cutorch/lib/THC/THCTensorRandom.cu(250): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/tmp/luarocks_cutorch-scm-1-4622/cutorch/lib/THC/THCTensorRandom.cu(264): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/tmp/luarocks_cutorch-scm-1-4622/cutorch/lib/THC/THCTensorRandom.cu(278): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/tmp/luarocks_cutorch-scm-1-4622/cutorch/lib/THC/THCTensorRandom.cu(293): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

/tmp/luarocks_cutorch-scm-1-4622/cutorch/lib/THC/THCTensorRandom.cu(308): error: more than one instance of overloaded function "min" matches the argument list:
            function "min(int, int)"
            function "min(unsigned int, unsigned int)"
            function "min(int, unsigned int)"
            function "min(unsigned int, int)"
            function "min(long long, long long)"
            function "min(unsigned long long, unsigned long long)"
            function "min(long long, unsigned long long)"
            function "min(unsigned long long, long long)"
            function "min(float, float)"
            function "min(double, double)"
            function "min(float, double)"
            function "min(double, float)"
            argument types are: (ptrdiff_t, ptrdiff_t)

**Comment by BTNC** [comment]
@ambarpal @hworang77 , the PR to fix the issue is not merged yet. Temporarily, could you change line 241 in file cutorch/lib/THC/THCTensorRandom.cu to:
`#define NUM_BLOCKS min((int)THCCeilDiv(size, (ptrdiff_t) BLOCK_SIZE), MAX_NUM_BLOCKS)` and retry?

**Comment by soumith** [comment]
hi there. this issue should now be fixed in master. the PR to fix this has been merged.

**Comment by pelekageorgia** [comment]
Hi there, I've tried to build the new version and now I have the following error:

```
~/lib/torch/sources/extra/cutorch/init.c: In function ‘cutorch_hasHalfInstructions’:
~/lib/torch/sources/extra/cutorch/init.c:904:3: error: implicit declaration of function ‘THC_nativeHalfInstructions’ [-Werror=implicit-function-declaration]
   lua_pushboolean(L, THC_nativeHalfInstructions(state));
   ^
~/lib/torch/sources/extra/cutorch/init.c: In function ‘cutorch_hasFastHalfInstructions’:
~/lib/torch/sources/extra/cutorch/init.c:910:3: error: implicit declaration of function ‘THC_fastHalfInstructions’ [-Werror=implicit-function-declaration]
   lua_pushboolean(L, THC_fastHalfInstructions(state));
   ^
cc1: some warnings being treated as errors
make[2]: *** [CMakeFiles/cutorch.dir/init.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/cutorch.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
```

**Comment by hworang77** [comment]
@pelekageorgia 
Hi, I had the same problem installing the merged master version. However, as you can recognize in the error message, you can compile after removing -Werror=implicit-function-declaration flag in CMakeList.txt file.

The error you got is a warning treated as an error.

**Comment by soumith** [comment]
lua_pushboolean should exist as part of your standard LuaJIT 2.1 or Lua 5.2 installation. I dont know why you dont have it as part of your Lua.

**Comment by soumith** [comment]
oh it cant find THC_nativeHalfInstructions, which is weird. cutorch should've just compiled it, it is part of cutorch source here: 

https://github.com/torch/cutorch/blob/f479a676bba3979d7606cf517bb3d855ad38859f/lib/THC/THCHalf.h#L22

Actually, i think i know the issue. this will fail for CUDA < 7.5

**Comment by soumith** [comment]
@pelekageorgia this is now fixed in master via https://github.com/torch/cutorch/commit/9d35ccb9c3690f6b98acdaaec73b142da47f6665

To fix it:

luarocks install cutorch

**Comment by pelekageorgia** [comment]
Yes actually my setup is with cuda 7, i'll give it a try again with the fix. Thanks!
